name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'infrastructure'
      - 'automation'
      - 'documentation'
      - 'code refinement'
  - title: '🏎 Performance'
    labels: 
      - 'performance'
  - title: 'Security'
    labels: 
      - 'security'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'bugfix'
      - 'fix'
      - 'maintenance'
      - 'documentation'
      - 'code refinement'
      - 'infrastructure'
      - 'performance'
      - 'security'
  default: patch
autolabeler:
  - label: 'breaking'
    title:
      - '/breaking/i'
  - label: 'enhancement'
    title:
      - '/enhancement/i'
      - '/feature/i'
  - label: 'bugfix'
    title:
      - '/fix/i'
      - '/bug/i'
      - '/regression/i'
  - label: 'infrastructure'
    title:
      - '/infrastructure/i'
  - label: 'documentation'
    title:
      - '/doc/i'
  - label: 'code refinement'
    title:
      - '/refine/i'
      - '/clean/i'
  - label: 'performance'
    title:
      - '/perf/i'
  - label: 'security'
    title:
      - '/security/i'
template: |
  # Changelog ...
  $CHANGES
